import json

exported_variables = [
    "MYSQL_ROOT_PASSWORD",

    "WIREGUARD_PATH",
    "WG_SERVER_PUBLIC_KEY",
    "WG_ENDPOINT",
    "WG_ALLOWED_IPS",
    "WG_NAME",
    "WG_LISTENPORT",
]

def read_server_config() -> dict:
    """
    load in the server-config file
    """
    with open("servers-config.json", "r") as file:
        data = json.load(file)

    return data

def add_export(export_str: str, export_key: str, export_value: str) -> str:
    """
    Add:
        export <key>="<value>"
    """
    return export_str + "\n" + "export " + export_key + "=" + "\"" + export_value + "\""

def create_export_file(data: dict) -> None:
    """
    create an exports.sh file
    """
    export_file_str = "#!/bin/bash\n"
    export_file_str += "#\n"
    export_file_str += "# Auto-generated by exports.py\n"
    export_file_str += "# Variables that are exported to be used by other scripts\n"
    for key,value in data.items():
        if key in exported_variables:
            export_file_str = add_export(export_file_str, str(key), str(value))

    file = open("exports.sh", "w")
    file.write(export_file_str)
    file.close()

if __name__ == "__main__":
    # This will generate an exports.sh file that can be run to export environment variables
    data = read_server_config()
    create_export_file(data)
