#!/bin/bash
#
# Auto-generated by exports.py
# Variables that are exported to be used by other scripts

export HOME_SERVER_DIR="~/HOME-SERVER-SERVICES"
export MYSQL_ROOT_PASSWORD="mysql_root_password"
export WIREGUARD_PATH="/etc/wireguard"
export WG_SERVER_PUBLIC_KEY="wg_server_public_key"
export WG_ENDPOINT="endpoint"
export WG_ALLOWED_IPS="0.0.0.0/0,::/0"
export WG_NAME="wg0"
export WG_LISTENPORT="51820"
export BASE_USER="ubuntu"

# Hadoop Parameters
export HADOOP_USERNAME="hadoop"
export HADOOP_USER_PASSWORD="hadoop"
export HADOOP_VERSION="hadoop-3.3.6"
export HADOOP_LOCATION="/opt/hadoop"
export HADOOP_MASTER_IP="192.168.64.5"